insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('5008 Kim Point', 'Panzhuang', 'sagittis', 'Quincy Pass', '1') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('2208 Hovde Terrace', 'Aranyaprathet', 'interdum mauris', 'Delladonna Junction', '2') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('48006 Sugar Avenue', 'Zhavoronki', 'sociis natoque', 'Summerview Circle', '3') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('25800 Laurel Circle', 'Lamut', 'maecenas', 'Starling Alley', '4') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('2 Knutson Alley', 'Canhas', 'in hac', '7th Junction', '1') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('9 Briar Crest Road', 'Xinzhou', 'commodo', 'Dapin Terrace', '5') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('679 Kropf Parkway', 'Zhongluotan', 'suscipit nulla', 'Nova Drive', '2') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('621 Cascade Street', 'Cinyawar', 'nulla justo aliquam', 'American Ash Avenue', '3') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('873 Brentwood Center', 'Santa Cruz', 'nulla', 'Elgar Street', '6') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('87762 Caliangt Circle', 'Anfeng', 'sodales scelerisque mauris', 'Talmadge Lane', '4') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('9525 Arapahoe Lane', 'Abonnema', 'pretium', 'Cardinal Parkway', '1') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('08144 Dottie Hill', 'Bulod', 'dis parturient montes', 'Springview Road', '7') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('2 Sunnyside Alley', 'Baisangguan', 'venenatis lacinia', 'Messerschmidt Park', '2') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('05 Milwaukee Drive', 'Guadalupe Victoria', 'nascetur ridiculus mus', '7th Junction', '5') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('31 Monica Center', 'Descalvado', 'pharetra', 'Division Crossing', '6') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('98010 Forest Way', 'Panshi', 'ut', 'Caliangt Street', '3') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('94201 Drewry Parkway', 'Woerden', 'justo maecenas rhoncus', 'West Way', '8') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('8 Sachtjen Alley', 'Banyubang', 'porttitor', 'Logan Circle', '4') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('65737 Anthes Parkway', 'Choloma', 'aenean lectus', 'Melvin Place', '9') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('55 Bobwhite Crossing', 'Boromlya', 'lorem integer tincidunt', 'Farmco Parkway', '10') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('6 Loftsgordon Way', 'Johor Bahru', 'venenatis non', 'Melrose Road', '11') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('238 Fallview Avenue', 'Ladushkin', 'morbi a', 'Mayfield Hill', '7') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('5 Carpenter Crossing', 'Velyka Pysarivka', 'amet erat', 'Boyd Lane', '12') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('2 Myrtle Avenue', 'Banjar Lalangpasek', 'sed justo pellentesque', 'Oxford Drive', '8') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('33244 Quincy Trail', 'Sukadana', 'donec', 'Manufacturers Avenue', '5') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('282 Melody Pass', 'Leones', 'dictumst maecenas ut', 'Mifflin Park', '6') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('70 Springs Hill', 'Aya', 'donec semper sapien', 'Anniversary Park', '13') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('7 Fairfield Pass', 'Caper', 'ut', 'Loftsgordon Court', '9') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('6064 Dunning Junction', 'Dmitriyevka', 'vulputate', 'Prentice Circle', '10') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('424 Kropf Circle', 'Urus-Martan', 'neque duis bibendum', 'Mccormick Circle', '11') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('60516 Katie Hill', 'Churubamba', 'diam erat', 'International Road', '14') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('71961 Kipling Alley', 'Tianhe', 'commodo placerat praesent', 'Sunnyside Plaza', '12') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('302 Annamark Plaza', 'Wiesbaden', 'ligula suspendisse', 'Quincy Trail', '13') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('528 Stephen Center', 'Babakankadu', 'vestibulum ante ipsum', 'Arkansas Plaza', '15') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('42162 La Follette Pass', 'Bambari', 'ac lobortis', 'Havey Court', '16') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('47868 Hovde Circle', 'Atami', 'id', 'Daystar Court', '7') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('9 Oakridge Hill', 'Cikaras', 'felis', 'Donald Terrace', '14') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('9328 Mayer Center', 'Praszka', 'ipsum dolor sit', 'Wayridge Court', '8') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('020 Glacier Hill Junction', 'Haoxinying', 'ultrices libero non', 'Prairieview Circle', '9') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('6904 Cherokee Plaza', 'Margen', 'turpis elementum ligula', 'Quincy Parkway', '15') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('7065 4th Court', 'Tejakalapa', 'nullam molestie nibh', 'West Way', '10') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('831 Killdeer Avenue', 'Falun', 'potenti in', 'Loftsgordon Center', '11') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('3 Nancy Trail', 'Oslo', 'potenti cras in', 'Sauthoff Point', '16') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('2516 West Point', 'Pamplona', 'sem praesent', 'Almo Terrace', '12') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('86 Crest Line Way', 'Emiliano Zapata', 'nulla quisque', 'Bobwhite Point', '17') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('1734 Fisk Pass', 'Kendal', 'pede justo', 'Charing Cross Crossing', '18') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('0 Tennyson Circle', 'Hongqi Yingzi', 'faucibus', 'Glacier Hill Alley', '17') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('93 Bunker Hill Circle', 'Fangqiang', 'mi in porttitor', 'Loeprich Pass', '13') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('1996 Florence Terrace', 'Limoges', 'proin risus', 'Chive Pass', '18') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('414 Bobwhite Terrace', 'Uzlovaya', 'arcu', 'Stone Corner Parkway', '19') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('4 Oneill Trail', 'Haiyang', 'sagittis dui', 'Brentwood Center', '19') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('68005 Welch Terrace', 'Hengxi', 'nisi', 'Claremont Road', '20') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('1434 Macpherson Trail', 'Cibinong', 'amet nulla', 'Del Sol Crossing', '20') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('770 Erie Alley', 'Shamkhor', 'mi sit amet', 'Quincy Parkway', '21') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('7 Graceland Terrace', 'Bagok', 'consectetuer adipiscing elit', 'Ryan Circle', '14') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('391 Truax Alley', 'Baicaogou', 'mauris vulputate elementum', 'Loeprich Alley', '15') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('09 Red Cloud Court', 'Bilozerka', 'risus dapibus', 'Brickson Park Plaza', '21') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('450 Coleman Hill', 'Kongsvinger', 'semper interdum mauris', 'Pepper Wood Point', '22') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('3175 Red Cloud Avenue', 'Rokitno', 'justo aliquam quis', 'Nevada Road', '22') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('556 Valley Edge Pass', 'Buenavista', 'in faucibus', 'Dixon Park', '16') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('8 Transport Park', 'Gereshk', 'in felis', 'Harbort Drive', '17') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('1347 Hooker Place', 'Jiangkou', 'suscipit a feugiat', 'Atwood Place', '23') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('8724 Mariners Cove Park', 'Weiyuan', 'et', 'Westridge Point', '23') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('99 Hudson Way', 'Sukorejo', 'quis turpis sed', 'Stephen Center', '24') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('372 Green Ridge Avenue', 'Los Nogales', 'libero non mattis', 'Brentwood Center', '24') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('1 Marcy Pass', 'Fengmu', 'in', 'Rutledge Plaza', '25') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('86927 Shasta Lane', 'Beoga', 'feugiat non', 'Anniversary Court', '25') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('5700 Cherokee Court', 'Ogurugu', 'vestibulum sed magna', 'Jenna Terrace', '18') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('419 Lerdahl Parkway', 'Nyangao', 'cursus urna', 'Glendale Center', '26') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('7 Sundown Center', 'Zhongchao', 'luctus tincidunt nulla', 'Iowa Drive', '26') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('618 Mayfield Trail', 'Sheli', 'augue vestibulum', 'Dapin Terrace', '27') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('267 Almo Terrace', 'Cibeureum', 'pulvinar', 'Sugar Avenue', '19') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('33 Elka Point', 'Tambaksari', 'aliquam', 'Lakewood Gardens Plaza', '20') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('43 Hooker Alley', 'Zhuji', 'proin eu', 'Claremont Crossing', '28') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('032 Talmadge Lane', 'Trondheim', 'rutrum nulla', 'Crownhardt Drive', '29') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('092 Ridgeway Hill', 'Havana', 'felis donec', 'Ruskin Point', '30') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('906 Spaight Lane', 'Gedangan', 'turpis', 'Messerschmidt Court', '27') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('499 Armistice Center', 'Zaolin', 'vehicula consequat', 'Green Ridge Avenue', '21') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('0 Redwing Plaza', 'Taraco', 'nam', 'Stephen Circle', '31') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('39 Golf Course Plaza', 'Taklale', 'in magna bibendum', 'Warrior Parkway', '28') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('447 Coolidge Circle', 'Chiguayante', 'pede posuere nonummy', 'Ruskin Point', '29') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('6490 Moland Park', 'Tarata', 'risus auctor', 'Quincy Trail', '30') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('6 Loomis Lane', 'Pomabamba', 'aliquam', 'Messerschmidt Court', '22') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('29222 Summerview Circle', 'Skhodnya', 'porttitor id', 'Warrior Parkway', '23') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('57841 Delaware Way', 'Melres', 'pede posuere nonummy', 'Trailsway Hill', '31') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('743 Dayton Park', 'Cimanggu', 'pellentesque', 'Old Gate Crossing', '32') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('04035 Old Shore Drive', 'Kinsale', 'eget', 'Melrose Road', '33') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('2492 Stuart Court', 'Aleg', 'justo eu massa', 'Oxford Drive', '24') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('19 Cherokee Place', 'Zhonghuopu', 'est risus auctor', 'Everett Hill', '25') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('5345 Southridge Center', 'La Ligua', 'integer', 'Oak Road', '34') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('64142 Del Mar Drive', 'Kiten', 'cursus vestibulum proin', 'Corscot Parkway', '35') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('5007 Del Sol Drive', 'Cabinteely', 'nulla mollis molestie', 'American Ash Avenue', '36') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('8 Grayhawk Trail', 'Tabor', 'pretium iaculis', 'Fallview Avenue', '32') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('71 Barnett Alley', 'Hegarmanah', 'vel', 'Karstens Junction', '33') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('008 Helena Drive', 'Mshinskaya', 'ultrices', '5th Pass', '37') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('06503 Dottie Court', 'Pampierstad', 'magna at nunc', 'Forster Road', '38') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('79 Meadow Vale Place', 'Wuli', 'montes nascetur ridiculus', 'Crownhardt Parkway', '26') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('15262 Grasskamp Drive', 'Staraya Russa', 'quam nec dui', 'Northridge Pass', '27') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('1 Stuart Hill', 'Tangchi', 'venenatis lacinia', 'Steensland Way', '39') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('5 Artisan Alley', 'Dhalie', 'vel sem', 'Melby Avenue', '40') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('32237 Memorial Circle', 'Cikadu', 'quis turpis eget', 'Dottie Hill', '28') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('7 Norway Maple Place', 'Wenshao', 'non', 'Harbort Lane', '41') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('880 Norway Maple Center', 'Bromma', 'sodales sed tincidunt', 'Jackson Trail', '34') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('59521 Hermina Pass', 'Punkalaidun', 'praesent id', 'Anzinger Pass', '35') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('224 Laurel Hill', 'Kolpashevo', 'sed vestibulum', 'Buell Way', '36') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('547 American Place', 'Doushan', 'aliquet', 'Stone Corner Way', '42') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('944 Summit Trail', 'Grazhdanskoye', 'dolor sit amet', 'Upham Court', '43') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('60878 Farwell Hill', 'Vanino', 'sapien', 'Everett Lane', '29') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('0 Northwestern Trail', 'San Fabian', 'quisque arcu libero', 'Elka Way', '37') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('409 Ruskin Point', 'Malin', 'ornare imperdiet', 'Granby Avenue', '38') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, funcionarios_id) values ('01215 West Place', 'Chicago', 'lacus', 'Lakewood Gardens Plaza', '39') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('2049 Corben Crossing', 'Sakata', 'pede venenatis non', 'Atwood Alley', '44') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, restaurantes_id) values ('81622 Raven Terrace', 'Presidente Dutra', 'tempus vivamus', 'Northwestern Lane', '30') ON CONFLICT DO NOTHING;
insert into enderecos (logradouro, cidade, bairro, estado, clientes_id) values ('2 Garrison Way', 'Pandansari', 'turpis integer aliquet', 'Kings Center', '45') ON CONFLICT DO NOTHING;


-- SELECT * FROM  enderecos
-- truncate enderecos
-- RESTART IDENTITY