--select * from restaurantes; 30
--select * from clientes 45
-- select * from mesas
--select * from mesas

--TRUNCATE mesas RESTART IDENTITY CASCADE

insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 10, 'Terraço', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 15, 'Área externa', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 16, null, 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 18, null, 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 21, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 22, null, 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 23, 'Terraço', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 29, 'Área interna', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 32, 'Área externa', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 37, null, 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 43, 'Varanda', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 5, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 51, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 55, 'Varanda', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 56, null, 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 57, null, 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 65, 'Área interna', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 68, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 69, 'Terraço', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 70, 'Área externa', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 73, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 74, 'Área externa', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 76, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 77, 'Área externa', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 80, 'Área interna', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 82, 'Área externa', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 86, 'Varanda', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 90, 'Área interna', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 92, 'Área externa', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 93, 'Vip', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 96, 'Terraço', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 97, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 98, 'Vip', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (1, 99, 'Terraço', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 14, 'Área interna', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 15, 'Varanda', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 16, 'Área interna', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 2, 'Área interna', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 25, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 31, 'Área interna', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 33, null, 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 34, null, 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 42, 'Área interna', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 47, 'Varanda', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 53, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 62, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 66, 'Terraço', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 67, 'Área externa', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 68, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 69, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 71, null, 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 83, 'Vip', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 85, 'Área interna', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 87, 'Área externa', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 88, 'Área interna', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 90, 'Área externa', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 92, 'Vip', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 94, 'Área externa', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (10, 95, 'Área externa', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 1, 'Vip', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 100, 'Varanda', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 19, null, 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 21, 'Área interna', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 26, 'Vip', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 3, 'Terraço', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 33, 'Terraço', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 38, 'Vip', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 40, 'Área interna', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 41, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 44, 'Terraço', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 48, 'Vip', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 49, 'Área interna', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 50, 'Varanda', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 54, null, 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 55, 'Vip', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 58, 'Área interna', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 59, 'Área externa', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 62, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 66, 'Terraço', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 67, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 68, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 7, 'Área externa', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 72, 'Área interna', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 76, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 77, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 79, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 8, 'Área interna', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 87, 'Vip', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 96, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 97, 'Área interna', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (11, 98, 'Vip', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 1, 'Varanda', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 12, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 14, 'Terraço', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 15, 'Vip', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 24, 'Área interna', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 27, null, 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 28, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 34, 'Terraço', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 37, 'Vip', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 44, 'Terraço', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 5, null, 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 50, 'Área externa', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 53, null, 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 54, 'Terraço', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 61, null, 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 63, 'Área interna', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 64, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 66, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 67, 'Terraço', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 69, 'Área interna', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 72, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 74, 'Área interna', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 77, 'Terraço', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 8, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 81, 'Área interna', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 84, 'Área interna', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 85, 'Varanda', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 87, 'Vip', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (12, 89, null, 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 14, 'Terraço', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 15, 'Terraço', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 2, 'Área interna', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 21, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 22, 'Vip', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 27, 'Área interna', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 32, 'Área interna', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 35, 'Varanda', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 37, null, 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 41, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 44, null, 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 49, 'Área interna', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 50, 'Terraço', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 51, 'Vip', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 52, 'Área interna', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 53, 'Área externa', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 58, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 69, 'Vip', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 7, 'Área externa', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 70, 'Terraço', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 76, 'Terraço', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 79, 'Área interna', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 85, 'Terraço', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 87, 'Área externa', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 88, 'Vip', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 94, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (13, 97, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 21, 'Área interna', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 25, 'Área interna', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 26, null, 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 37, 'Terraço', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 38, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 39, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 42, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 44, 'Varanda', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 45, null, 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 46, 'Vip', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 48, null, 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 49, 'Vip', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 51, 'Terraço', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 53, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 62, 'Área interna', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 63, 'Vip', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 66, 'Terraço', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 69, 'Varanda', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 73, 'Terraço', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 75, null, 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 78, 'Área externa', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 8, 'Área externa', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 91, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 92, null, 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (14, 95, 'Terraço', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 15, 'Vip', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 16, 'Vip', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 17, null, 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 22, 'Área externa', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 24, 'Área interna', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 27, 'Área externa', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 3, 'Terraço', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 32, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 33, 'Área interna', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 36, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 4, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 41, 'Área interna', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 42, 'Varanda', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 43, 'Terraço', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 45, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 50, 'Área externa', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 51, 'Varanda', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 62, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 63, 'Terraço', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 65, 'Área interna', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 7, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 74, null, 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 89, 'Terraço', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 9, 'Área interna', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 90, 'Vip', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 91, 'Terraço', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 96, 'Varanda', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (15, 98, 'Área externa', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 1, 'Varanda', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 29, 'Terraço', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 31, 'Área interna', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 32, null, 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 33, 'Terraço', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 34, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 40, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 41, 'Varanda', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 43, 'Terraço', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 46, 'Terraço', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 49, 'Varanda', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 50, 'Terraço', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 53, null, 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 54, null, 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 61, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 66, 'Vip', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 69, 'Área externa', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 71, 'Área interna', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 72, 'Vip', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 77, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 84, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 86, 'Varanda', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 93, 'Terraço', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 94, null, 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 95, 'Vip', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (16, 96, 'Terraço', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 1, null, 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 11, 'Vip', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 16, 'Varanda', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 18, null, 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 20, 'Área interna', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 21, 'Vip', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 27, null, 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 29, 'Área interna', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 3, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 31, 'Varanda', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 35, null, 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 37, 'Vip', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 38, 'Vip', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 39, 'Área interna', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 48, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 49, 'Terraço', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 52, null, 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 55, 'Vip', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 57, null, 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 59, null, 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 62, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 63, 'Varanda', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 64, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 65, 'Área externa', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 66, null, 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 68, 'Área interna', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 71, 'Terraço', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 75, 'Terraço', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 8, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 81, 'Vip', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 89, 'Área externa', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 90, 'Varanda', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (17, 91, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 1, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 100, 'Varanda', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 15, 'Vip', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 2, 'Área externa', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 21, null, 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 29, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 32, null, 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 34, 'Área externa', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 36, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 48, 'Área interna', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 49, 'Vip', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 51, 'Terraço', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 53, 'Área externa', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 54, 'Varanda', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 57, 'Área interna', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 58, 'Área externa', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 59, 'Área interna', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 63, 'Área externa', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 64, 'Área interna', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 79, 'Área interna', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 81, null, 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 83, 'Área externa', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 85, 'Varanda', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 92, 'Terraço', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 93, 'Terraço', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 94, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 95, 'Área externa', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (18, 96, null, 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 23, 'Vip', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 26, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 29, 'Área externa', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 30, 'Vip', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 33, 'Área interna', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 35, 'Vip', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 39, 'Área externa', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 4, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 42, 'Terraço', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 45, 'Área interna', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 52, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 58, 'Área externa', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 59, null, 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 65, null, 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 69, 'Terraço', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 8, 'Vip', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 84, 'Vip', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 86, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 92, 'Área externa', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (19, 98, null, 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 10, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 100, 'Terraço', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 13, 'Área interna', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 15, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 16, 'Varanda', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 23, 'Área externa', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 24, null, 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 30, null, 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 31, 'Área interna', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 32, 'Área externa', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 35, 'Área externa', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 37, null, 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 38, 'Área interna', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 45, 'Varanda', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 58, null, 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 59, 'Área interna', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 61, 'Área interna', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 65, 'Varanda', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 66, 'Área externa', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 7, 'Vip', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 70, null, 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 74, null, 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 75, 'Varanda', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 81, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 86, 'Vip', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 89, null, 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 9, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (2, 98, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 100, 'Vip', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 11, null, 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 2, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 20, 'Área interna', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 23, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 24, 'Vip', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 27, 'Terraço', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 28, 'Varanda', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 33, 'Terraço', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 35, 'Varanda', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 39, 'Área interna', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 41, 'Varanda', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 49, 'Vip', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 5, 'Área interna', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 51, null, 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 52, null, 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 54, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 55, null, 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 66, 'Vip', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 67, 'Área interna', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 79, 'Terraço', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 86, 'Terraço', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 87, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 88, 'Terraço', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 9, 'Vip', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 91, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 94, 'Área externa', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 95, null, 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 96, 'Varanda', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 98, 'Terraço', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (20, 99, 'Área interna', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 12, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 18, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 21, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 36, 'Área interna', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 4, 'Área externa', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 43, 'Vip', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 45, 'Terraço', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 46, null, 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 53, null, 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 56, null, 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 57, 'Terraço', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 63, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 64, 'Varanda', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 69, 'Área interna', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 70, null, 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 72, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 73, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 74, 'Vip', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 79, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 80, 'Área interna', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 81, 'Varanda', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 84, 'Terraço', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 87, 'Varanda', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 89, 'Terraço', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 9, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 92, 'Vip', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 95, 'Vip', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (21, 99, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 10, 'Terraço', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 100, 'Área interna', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 14, 'Varanda', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 15, 'Terraço', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 18, null, 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 19, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 2, 'Varanda', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 22, 'Área externa', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 26, 'Área externa', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 29, 'Área interna', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 30, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 4, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 42, 'Vip', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 5, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 50, 'Vip', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 51, 'Área externa', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 54, 'Varanda', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 55, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 59, 'Área externa', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 63, 'Área externa', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 64, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 65, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 66, 'Terraço', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 67, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 82, 'Terraço', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 85, 'Varanda', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 86, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 9, null, 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 95, 'Varanda', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 97, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (22, 98, 'Área interna', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 11, 'Terraço', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 13, 'Área interna', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 15, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 16, 'Terraço', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 2, 'Área interna', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 20, 'Varanda', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 24, 'Varanda', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 29, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 3, 'Área externa', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 30, 'Varanda', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 31, null, 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 35, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 40, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 42, null, 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 44, 'Vip', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 45, 'Varanda', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 46, 'Área interna', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 5, 'Terraço', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 54, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 55, 'Área externa', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 56, null, 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 6, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 60, 'Terraço', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 62, null, 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 64, 'Área interna', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 72, 'Área interna', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 75, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 8, 'Terraço', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 87, 'Vip', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 92, 'Terraço', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 96, 'Varanda', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (23, 99, 'Vip', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 11, 'Vip', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 15, 'Terraço', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 18, 'Varanda', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 2, 'Área interna', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 20, 'Vip', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 25, 'Terraço', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 26, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 34, 'Vip', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 38, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 39, 'Área interna', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 40, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 46, 'Terraço', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 5, 'Área externa', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 57, 'Varanda', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 58, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 6, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 63, 'Terraço', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 64, 'Vip', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 65, null, 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 66, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 67, 'Área externa', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 71, 'Varanda', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 73, null, 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 79, 'Varanda', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 80, null, 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 84, null, 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 87, 'Vip', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 91, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 93, 'Área externa', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 95, 'Área externa', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 97, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (24, 98, 'Área interna', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 16, 'Área interna', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 17, null, 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 19, 'Varanda', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 23, null, 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 35, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 40, null, 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 41, 'Vip', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 46, 'Varanda', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 48, 'Terraço', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 50, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 53, 'Terraço', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 59, 'Terraço', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 61, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 63, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 75, null, 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 80, null, 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 81, null, 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 84, 'Varanda', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 88, 'Vip', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 91, null, 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 92, 'Varanda', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (25, 96, 'Área externa', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 1, 'Terraço', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 10, null, 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 12, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 15, null, 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 16, 'Varanda', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 2, null, 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 24, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 29, 'Área interna', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 31, 'Vip', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 39, null, 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 44, 'Terraço', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 47, 'Varanda', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 49, 'Terraço', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 50, 'Terraço', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 51, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 54, 'Área interna', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 58, 'Terraço', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 6, null, 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 61, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 66, 'Área externa', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 69, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 72, 'Terraço', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 74, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 75, null, 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 78, 'Terraço', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 8, null, 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 80, 'Área interna', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 83, 'Área interna', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 89, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (26, 94, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 10, 'Área interna', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 100, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 13, 'Terraço', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 20, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 22, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 23, 'Terraço', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 24, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 29, 'Área externa', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 35, 'Varanda', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 36, 'Área interna', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 38, 'Varanda', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 4, 'Varanda', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 40, 'Vip', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 46, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 47, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 49, 'Área interna', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 50, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 52, 'Vip', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 57, 'Vip', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 60, 'Terraço', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 72, 'Vip', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 78, null, 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 8, 'Área interna', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 80, 'Vip', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 83, null, 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 85, 'Vip', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 86, null, 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 88, 'Terraço', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 95, null, 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (27, 96, 'Área interna', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 1, 'Terraço', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 10, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 15, 'Área externa', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 17, 'Terraço', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 24, null, 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 26, 'Varanda', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 27, 'Vip', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 28, 'Varanda', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 30, null, 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 41, 'Vip', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 50, 'Varanda', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 52, 'Varanda', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 54, 'Vip', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 6, 'Área externa', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 64, 'Área externa', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 74, 'Área interna', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 75, 'Varanda', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 77, 'Terraço', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 79, null, 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 8, 'Varanda', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 83, 'Área externa', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 85, 'Área interna', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 89, 'Área interna', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 9, 'Área interna', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 91, 'Terraço', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 96, 'Terraço', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (28, 98, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 11, 'Área interna', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 14, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 15, 'Varanda', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 16, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 17, 'Terraço', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 21, 'Área interna', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 22, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 27, 'Varanda', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 29, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 3, 'Vip', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 4, null, 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 41, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 42, 'Vip', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 46, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 48, null, 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 49, 'Vip', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 56, 'Área interna', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 66, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 67, 'Vip', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 72, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 75, 'Área externa', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 76, 'Área externa', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 79, 'Área externa', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 82, 'Área interna', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 83, 'Varanda', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 87, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 9, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (29, 90, 'Terraço', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 1, 'Terraço', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 10, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 11, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 12, 'Vip', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 17, 'Vip', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 18, 'Área externa', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 27, 'Terraço', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 33, 'Área interna', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 47, 'Terraço', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 54, 'Vip', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 6, 'Área interna', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 70, 'Área externa', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 77, 'Terraço', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 79, 'Área externa', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 80, 'Área interna', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 86, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 88, 'Terraço', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 89, null, 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 9, 'Vip', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 90, null, 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (3, 97, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 14, 'Área interna', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 15, 'Vip', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 24, 'Área externa', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 28, 'Área interna', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 29, 'Área externa', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 30, 'Área externa', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 31, 'Terraço', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 4, 'Varanda', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 41, null, 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 43, 'Varanda', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 44, 'Terraço', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 47, null, 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 48, null, 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 49, 'Vip', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 53, 'Área externa', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 55, 'Varanda', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 56, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 60, 'Terraço', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 64, null, 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 7, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 73, null, 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 75, 'Varanda', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 79, 'Área interna', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 8, 'Terraço', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 85, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 87, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 93, 'Vip', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (30, 94, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 100, 'Terraço', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 12, null, 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 26, 'Área interna', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 28, null, 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 29, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 31, 'Terraço', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 36, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 42, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 43, 'Área externa', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 44, 'Varanda', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 52, 'Varanda', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 56, null, 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 62, null, 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 65, 'Terraço', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 83, null, 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 84, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 89, 'Varanda', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 90, 'Vip', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (4, 95, 'Área interna', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 1, 'Área interna', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 18, 'Área externa', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 20, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 22, 'Área externa', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 3, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 30, 'Varanda', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 33, 'Área interna', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 34, 'Vip', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 45, 'Varanda', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 48, 'Área externa', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 51, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 54, 'Terraço', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 59, 'Área interna', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 61, null, 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 64, 'Área externa', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 66, null, 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 69, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 73, 'Área externa', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 74, 'Área interna', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 77, 'Terraço', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 78, 'Vip', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 79, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 81, 'Área interna', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 82, 'Varanda', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 83, 'Área externa', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 90, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 91, null, 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 92, 'Área externa', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (5, 94, 'Área interna', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 10, 'Área externa', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 13, 'Área externa', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 15, 'Área externa', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 17, 'Vip', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 19, null, 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 2, 'Vip', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 38, 'Vip', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 39, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 42, 'Varanda', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 43, 'Terraço', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 45, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 48, 'Terraço', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 49, 'Vip', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 53, 'Terraço', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 55, 'Varanda', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 57, 'Terraço', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 59, 'Área externa', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 66, 'Terraço', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 67, null, 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 70, 'Área interna', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 71, 'Varanda', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 72, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 75, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 77, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 78, 'Área externa', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 8, 'Terraço', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 82, null, 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 84, 'Vip', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 86, 'Varanda', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 87, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 88, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 91, 'Área externa', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 95, 'Terraço', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 98, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (6, 99, 'Varanda', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 10, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 12, 'Área externa', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 14, 'Área interna', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 16, 'Vip', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 17, 'Terraço', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 3, null, 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 31, 'Área interna', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 32, 'Área interna', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 39, 'Varanda', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 44, 'Área externa', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 48, 'Varanda', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 5, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 51, 'Área interna', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 53, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 55, 'Área externa', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 58, 'Varanda', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 59, 'Área externa', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 64, 'Área externa', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 67, 'Área interna', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 7, 'Varanda', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 70, 'Área externa', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 71, 'Área externa', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 79, null, 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 84, null, 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 85, 'Área externa', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 86, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 89, 'Terraço', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 9, 'Terraço', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 92, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 95, 'Área interna', 5);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 98, 'Área interna', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (7, 99, 'Área externa', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 10, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 16, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 20, 'Área interna', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 22, 'Vip', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 23, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 24, null, 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 29, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 3, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 38, null, 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 39, 'Terraço', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 4, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 42, 'Área interna', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 43, 'Área interna', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 52, 'Vip', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 53, 'Área externa', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 59, 'Varanda', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 62, null, 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 64, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 66, 'Vip', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 68, 'Vip', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 70, 'Varanda', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 75, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 76, 'Vip', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 8, 'Terraço', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 80, 'Varanda', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 82, null, 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 83, 'Terraço', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 84, 'Varanda', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 88, 'Área externa', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (8, 90, 'Vip', 10);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 11, 'Área externa', 12);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 12, null, 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 13, 'Vip', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 16, 'Vip', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 17, 'Varanda', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 19, 'Vip', 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 20, 'Área interna', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 25, 'Área externa', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 27, 'Área externa', 2);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 28, 'Terraço', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 30, null, 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 32, null, 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 34, 'Terraço', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 35, 'Varanda', 8);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 45, 'Terraço', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 46, 'Vip', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 5, 'Terraço', 6);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 53, 'Área externa', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 54, 'Vip', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 68, 'Varanda', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 7, null, 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 70, 'Varanda', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 72, null, 1);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 74, 'Terraço', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 76, 'Área interna', 3);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 82, 'Área interna', 9);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 83, 'Área interna', 11);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 85, 'Varanda', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 87, 'Vip', 4);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 96, 'Varanda', 7);
insert into mesas (id_restaurantes, numero_mesa, localizacao, capacidade) values (9, 97, null, 2);



