INSERT INTO public.funcoes (funcao) VALUES
    ('Garçom'),
    ('Cozinheiro Chefe'),
    ('Atendente de Caixa'),
    ('Chef de Pastelaria'),
    ('Bartender'),
    ('Host/Hostess'),
    ('Auxiliar de Cozinha'),
    ('Gerente de Restaurante'),
    ('Entregador'),
    ('Chefe de Sala'),
    ('Sommelier'),
    ('Auxiliar de Limpeza'),
    ('Chef de Churrasco'),
    ('Barista'),
    ('Maitre'),
    ('Chefe de Confeitaria'),
    ('Recepcionista'),
    ('Auxiliar de Bar'),
    ('Supervisor de Atendimento'),
    ('Auxiliar de Estoque'),
    ('Cozinheiro de Sushiman'),
    ('Auxiliar de Garçom'),
    ('Chefe de Buffet'),
    ('Pizzaiolo'),
    ('Auxiliar de Atendimento'),
    ('Chefe de Cozinha Rápida'),
    ('Host de Eventos'),
    ('Auxiliar de Logística'),
    ('Chefe de Pizzaria'),
    ('Atendente de Delivery'),
    ('Auxiliar de Eventos'),
    ('Chef de Comida Saudável'),
    ('Auxiliar de Produção'),
    ('Coordenador de Atendimento'),
    ('Chefe de Buffet Infantil'),
    ('Auxiliar de Qualidade'),
    ('Chef de Comida Vegana'),
    ('Supervisor de Cozinha'),
    ('Chefe de Cozinha Internacional');
	
	SELECT * FROM funcoes
